{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-example.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::578310434439:role/EKS-ALB-Role
{{ include "helm-example.labels" . | nindent 4 }}
{{- end -}}
